<?php
$z[0]=Array("global","",698,720);
$z[0][4]['name']="cfg_tel";
$z[1]=Array("global","",809,830);
$z[1][4]['name']="cfg_QQ";
$z[2]=Array("global","",836,863);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("arclist","\r\n    <h1><a style=\"background:url([field:img2/]) no-repeat 0 0;\" href=\"[field:lianjie2/]\">logo</a></h1>\r\n    ",1180,1407);
$z[3][4]['typeid']="17";
$z[3][4]['titlelen']="";
$z[3][4]['row']="1";
$z[3][4]['orderby']="";
$z[3][4]['addfields']="img2,lianjie2";
$z[3][4]['channelid']="7";
$z[4]=Array("global","",1556,1583);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("field","(@me==\"\")? @me=\" class='menu-a' \":@me=\"\";",1585,1676);
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[6]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n      ",1701,1907);
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='menu-a'>~typename~</a> </li>";
$z[7]=Array("global","",1978,2001);
$z[7][4]['name']="cfg_shop";
$z[8]=Array("global","",2058,2082);
$z[8][4]['name']="cfg_weibo";

?>