<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",328,357);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",394,453);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",577,612);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",653,674);
$z[5][4]['name']="content";
$z[6]=Array("include","",702,739);
$z[6][4]['filename']="footer.htm";

?>