<?php
$z[0]=Array("global","",623,649);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",674,701);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",738,768);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",1141,1176);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n		<li style=\"background:url('[field:img2/]') no-repeat center top\"><a href=\"[field:lianjie2/]\" target=\"_blank\">[field:title/]</a></li>\r\n		",1272,1529);
$z[4][4]['typeid']="18";
$z[4][4]['titlelen']="";
$z[4][4]['row']="6";
$z[4][4]['orderby']="";
$z[4][4]['addfields']="img2,lianjie2";
$z[4][4]['channelid']="7";
$z[5]=Array("arclist","\r\n         <li>\r\n                <a href=\"[field:lianjie2/]\" target=\"_blank\"><img src=\"[field:img2/]\" alt=\"[field:title/]\" /></a>\r\n                <p><a href=\"[field:lianjie2/]\" target=\"_blank\"><span class=\"span2\">[field:miaosu/]</span></a></p>\r\n            </li>\r\n            ",1755,2156);
$z[5][4]['typeid']="19";
$z[5][4]['titlelen']="";
$z[5][4]['row']="3";
$z[5][4]['orderby']="";
$z[5][4]['addfields']="img2,lianjie2,miaosu";
$z[5][4]['channelid']="7";
$z[6]=Array("include","",2753,2790);
$z[6][4]['filename']="footer.htm";

?>