<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",328,357);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",394,453);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",591,626);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",691,712);
$z[5][4]['name']="content";
$z[6]=Array("channel","\r\n               <li class=\"line2\" ><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                ",873,1101);
$z[6][4]['type']="sun";
$z[6][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a> </li>";
$z[7]=Array("list","\r\n                	<li>\r\n                    		<a href=\"[field:arcurl/]\" class=\"img\" target=\"_blank\"><img src=\"[field:img1/]\" style=\"width:310px;height:268px;\" alt=\"[field:title/]产品图片\" /></a>\r\n                        	<p><a href=\"[field:arcurl/]\" target=\"_blank\"><span>[field:title/]</span><em>[field:gongxiao/]</em></a></p>\r\n                    	</li>\r\n                        ",1262,1693);
$z[7][4]['row']="6";
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",1810,1884);
$z[8][4]['istitem']="index,pre,next,pageno,end,option,";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1953,1990);
$z[9][4]['filename']="footer.htm";

?>