<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",328,357);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",394,453);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",598,633);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",713,734);
$z[5][4]['name']="content";
$z[6]=Array("list","\r\n            	<li>\r\n                	<a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a>\r\n                    <h4><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h4>\r\n                    <p><a href=\"[field:arcurl/]\" target=\"_blank\">[field:description/]</a></p>\r\n                </li>\r\n				",902,1297);
$z[6][4]['row']="6";
$z[6][4]['pagesize']="6";
$z[7]=Array("pagelist","",1484,1558);
$z[7][4]['istitem']="index,pre,next,pageno,end,option,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",1636,1673);
$z[8][4]['filename']="footer.htm";

?>